config/routes.rb
Rails.application.routes.draw do

  resources :boards do

    resources :stories do
      resources :tasks
    end

    resources :steps
  end

  devise_for :users

  root to: 'boards#index'
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many   :steps, dependent: :destroy

  validates :name, presence: true

  scope :accessible_for, -> (user_id) do
    where([ "boards.user_id = :user_id OR boards.is_private IS NOT TRUE", user_id: user_id ])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :board_is_accessible_for_user?, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.accessible_for(current_user.id)
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    def board_is_accessible_for_user?
      if @board.is_private? && @board.owner != current_user
        flash[:notice] = t('.errors_messages.access_denied')
        redirect_to boards_url
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.fetch(:board, [:name]).permit!
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
  def table_board_for_user(board, &block)
    content_class = board.owner == current_user ? 'success' : ''
    content_tag(:tr, class: content_class) do
      yield
    end
  end
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.text_field :name, placeholder: 'board name', class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :is_private do %> 
      <%= f.check_box :is_private %>
      is private?
      <% end %>
  </div>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/boards/edit.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <div class='row'>
      <div class='col-md-8'>
        <h1>Edit Board</h1>
      </div>
      <div class='col-md-4'>
        <div class='action-buttons'>
          <%= link_to t('.actions.back'), boards_path, class: 'btn btn-warning' %>
        </div>
      </div>
  </div>
</div>
<div class='board-container'>
  <%= render 'form' %>
</div>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <div class='row'>
      <div class='col-md-8'>
        <h1>Listing Boards</h1>
      </div>
  </div>
</div>
<div class='board-container'>
  <table class="table table-bordered">
    <thead>
      <th>Name</th>
      <th>Edit</th>
      <th>Destroy</th>
    </thead>
    <tbody>
      <% @boards.each do |board| %>
        <%= table_board_for_user(board) do %>
          <td><%= link_to board.name, board %></td>
          <% if board.owner == current_user %>
            <td><%= link_to 'Edit', edit_board_path(board), class: 'btn btn-primary' %></td>
            <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Board', new_board_path, class: 'btn btn-primary' %>

app/views/boards/new.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <div class='row'>
      <div class='col-md-8'>
        <h1>New Board</h1>
      </div>
      <div class='col-md-4'>
        <div class='action-buttons'>
          <%= link_to t('.actions.back'), boards_path, class: 'btn btn-warning' %>
        </div>
      </div>
  </div>
</div>
<div class='board-container'>
  <%= render 'form' %>
</div>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <div class='row'>
      <div class='col-md-4'>
        <h1><%= @board.name %></h1>
      </div>
      <div class='col-md-8'>
        <div class='action-buttons'>
          <div class='new-step-form'></div>
          <%= link_to t('.actions.new_step'), 
            new_board_step_path(@board), class: 'btn btn-success' %> |
          <% if @board.owner == current_user %>
            <%= link_to t('.actions.edit'), edit_board_path(@board), class: 'btn btn-primary' %> |
          <% end %>
          <%= link_to t('.actions.back'), boards_path, class: 'btn btn-warning' %>
        </div>
      </div>
  </div>
</div>
<div class='board-container'>
  <%= render partial: 'steps/list', locals: { steps: @board.steps }  %>
</div>
<div id='story-modal'></div>